PANDAS TUTORIAL

In [1]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
dataframe = pd.read_csv("Salaries.csv")

NUMPY TUTORIAL

In [1]:
import numpy as np

In [7]:
a = np.array([1,2,3])
b = np.array([2,3,4])
c = a*b
print(c)

[ 2  6 12]


In [18]:
#2D array
d = np.array([[1.2,3.4,5.6],
              [2.3,4.5,6.7]], dtype='int32')
print(d)
print("Dimension is", d.ndim)
print("Shape is", d.shape)
print("Datatype is", d.dtype)
print(d.itemsize, d.size)

[[1 3 5]
 [2 4 6]]
Dimension is 2
Shape is (2, 3)
Datatype is int32
4 6


In [22]:
#Accessing, changing specific elements of an array
x = np.array([[1,2,3,4,5,6],
             [3,4,5,6,7,8]])
print(x)
x.shape

[[1 2 3 4 5 6]
 [3 4 5 6 7 8]]


(2, 6)

In [26]:
#get a specific element
x[0,3]

4

In [29]:
x[1, 0:3]

array([3, 4, 5])

In [31]:
x[ : ,2]

array([3, 5])

In [39]:
#Intermidate
print(x)
x[0, 1:6:2]

[[1 2 3 4 5 6]
 [3 4 5 6 7 8]]


array([2, 4, 6])

In [43]:
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [45]:
np.full_like(a, 4)

array([4, 4, 4])

In [52]:
np.random.randint(15, size=(4,4))

array([[ 9, 12, 10, 12],
       [ 4,  7, 14,  3],
       [14, 10,  3,  1],
       [10,  3,  2, 10]])

In [57]:
output = np.ones((5,5), dtype='int32')
print(output)

z = np.zeros((3,3), dtype='int32')
z[1,1]=9
print(z)

output[1:4, 1:4] = z
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#Linear algebra

In [65]:
a = np.ones((2,2))

b = np.full((2,3),4)

np.matmul(a,b)

array([[8., 8., 8.],
       [8., 8., 8.]])